name: pApUsageReview
on: [pull_request]

jobs:
  pApUsageReview:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: to-s/pApUsageReview@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
